# copied from django-cte
name: entity tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master,develop]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ['3.8', '3.9', '3.10']
        # Time to switch to pytest or nose2??
        # nosetests is broken on 3.11
        # AttributeError: module 'collections' has no attribute 'Callable'
        # https://github.com/nose-devs/nose/issues/1099
        django:
          - 'Django~=3.2.0'
          - 'Django~=4.0.0'
          - 'Django~=4.1.0'
          - 'Django~=4.2.0'
        psycopg:
          - 'psycopg2>2.9'
          - 'psycopg>=3.1.8'
        experimental: [false]
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Setup
      run: |
        python --version
        pip install --upgrade pip wheel
        pip install -r requirements/requirements.txt
        pip install -r requirements/requirements-testing.txt
        pip install "${{ matrix.django }}"
        pip uninstall psycopg psycopg2 && pip install "${{ matrix.psycopg }}"
        pip freeze
    - name: Run tests
      env:
        DB_SETTINGS: >-
          {
            "ENGINE":"django.db.backends.postgresql",
            "NAME":"entity",
            "USER":"postgres",
            "PASSWORD":"postgres",
            "HOST":"localhost",
            "PORT":"5432"
          }
      run: |
        coverage run manage.py test entity
        coverage report --fail-under=99
      continue-on-error: ${{ matrix.experimental }}
    - name: Check style
      run: flake8 entity
